### ISSUE TITLE
Make a doctrine phase view.

### ISSUE THREAD

**Issue by tasshin** [HiredThought/evolve#4]
The doctrine tool would be more useful if it were split up into phases. 

![image](https://user-images.githubusercontent.com/2863138/48997851-2228d800-f106-11e8-9240-ef76fc89369a.png)

We should probably also split out the doctrine page but that's a separate issue.

**Comment by tasshin** [comment]
Here is the data that would be useful for adding not only doctrine but also climatic patterns and gameplay (and a glossary?):
https://docs.google.com/spreadsheets/d/1iUjZTCCv1KsgQ5VNohtU1c3BpW7pwh7N_FDgJimjHF8/edit#gid=21887705

Also:
Technical: not HTML/Bootstrap - tables?
Pedagogy: Stages 1-5

Step 1 — The cycle
Step 2 — Learn the landscape
Step 3 — Learn and use climatic patterns
Step 4 — Learn and use doctrine
Step 5 — Learn and use gameplay

**Comment by bemosior** [comment]
This is great! My next step is to pay attention to what it would take from a technical standpoint to not require hand-editing html — a goofy hack I used just to get the original out into the wild.

**Comment by tasshin** [comment]
RE: glossary - just saw this: https://community.wardleymaps.com/t/mapping-glossary/280

**Comment by bemosior** [comment]
You and I covered all the above in the new version, so I think it's safe to close this.
